version: "3.8"

services:
#  backend:
#    depends_on:
#      - db
#    build: .
#    restart: unless-stopped
#    env_file: .env
#    ports:
#      - ${BACKEND_PORT}:${BACKEND_PORT}
#    environment:
#      DB_HOST: db
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PWD}
#      DB_NAME: ${DB_NAME}
#      DB_PORT: ${DB_PORT}
#    tty: true

  db:
    image: mysql:8.2.0
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local